### ISSUE TITLE
Installation procedure is not provided

### ISSUE THREAD

**Issue by solewniczak** [mcalus3/AntScheduler#1]
The README file doesn't provide a complete installation instruction. It should contain information how to use setup.py and how to run the installed program (there is no file main.py in the project directory nor the instructions how to run package antscheduler).

**Comment by mcalus3** [comment]
You can use setup.py to install antscheduler and its dependencies as a Python packages by invoking it with argument "install" (look it up in --help). However there is an yet unresolved issue in setuptools  that raises an error during downloading PyQt5 that way. To get it done:
1. download packages graphviz and PyQt5 through pip as specified in readme (you have pip, it comes with Python 3).
2. The script doesn't have to be installed as a package to be used, after downloading the dependencies just run the &#95;&#95;main&#95;&#95;.py file in package (folder) antscheduler (i have corrected a typo in readme).
3. You can run it also by invoking the "antscheduler" folder as if it was a script (package invoking).
